apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: test
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: user-management
          ports:
            - containerPort: 5432
